# Generated by Django 5.2.8 on 2025-12-05 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('publish_post', 'Can publish post')]},
        ),
    ]
